### ISSUE TITLE
可以同翻译

### ISSUE THREAD

**Issue by SuperSupeng** [DonaldDai/Bokeh-CN#3]
还在做这个事情么。 可以同步来翻译
SuperSupeng

**Comment by DonaldDai** [comment]
当时翻译的文档版本很久了，和现在版本对比，接口都已经不太一样了，不打算继续翻译。想重新开始一个较近的版本翻译，有兴趣可以一起来。

**Comment by SuperSupeng** [comment]
可以到时候一起做吧
